version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true
  
branches:
  only:
  - ci-debug
  - master
  
clone_depth: 1

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
- choco install redis-64
- redis-server --service-install
- redis-server --service-start
- nuget restore

configuration: Release

build:
  verbosity: minimal
  
deploy:
- provider: NuGet
  api_key:
    secure: 8nOJ8wjmitnOcDwlirh5QLHECezb9AQgSzbXbBsNkOBGhtOxz1WDQKBDOZXIhoM9
  on:
    branch: master