# Set semantic version number according to change made
#
# format: MAJOR.MINOR.PATCH
#
# Conventions: Major - Increment for breaking change in public interface
#			   Minor - Increment for backwards-compatible new feature
#			   Patch - Increment for build (automatically by Appveyor)

version: 3.0.{build}

pull_requests:
  do_not_increment_build_number: true
  
clone_depth: 1

# Add version to .NET Standard projects
dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

# Add version to test projects build with .NET Full framework
assembly_info:
  patch: true
  file: 'tests\**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - choco install redis-64
  - redis-server --service-install
  - redis-server --service-start
  - nuget restore

configuration: Release

build_script:
  - cmd: dotnet build

test:
  assemblies:
    - 'tests\**\*.Tests.dll'
    - 'tests\**\*.IntegrationTests.dll'

artifacts:
  - path: 'src\**\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: 8nOJ8wjmitnOcDwlirh5QLHECezb9AQgSzbXbBsNkOBGhtOxz1WDQKBDOZXIhoM9
  on:
    branch: master
    
on_finish:
  # https://www.appveyor.com/docs/how-to/rdp-to-build-worker
  - ps: |
      If ($env:APPVEYOR_REPO_BRANCH -eq 'ci-debug') 
      { 
        $blockRdp = $true
        iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      }
      